### ISSUE TITLE
How to make discovery Non-dismissable 

### ISSUE THREAD

**Issue by crushman1** [ayalma/feature_discovery#11]
Hello, 
Is it possible to disable the ability to dismiss the discovery?

**Comment by axel-op** [comment]
Hi, 
If your `onDismiss` function returns `false`, then nothing happens :)

**Comment by crushman1** [comment]
Works perfectly!

**Comment by axel-op** [comment]
> Works perfectly! For people who wandering how to implement : `onDismiss: ()async{return false;}`

Or even shorter: `() async => false`
