### ISSUE TITLE
clearPreferences not working?

### ISSUE THREAD

**Issue by jdeltoft** [ayalma/feature_discovery#16]
I'm unclear how it keeps track of what features you've already discovered.  I haven't looked at the code yet, but I assumed it was using shared prefs to just mark which feature id's were already shown?  So then I assume doing something like this would allow that to be shown again?  Say if a user wanted to see all the feature discoveries again.

```
                                  Container(
                                    //width: double.infinity,
                                    height: 60,
                                    padding: EdgeInsets.symmetric(
                                        vertical: 6.0, horizontal: 20.0),
                                    child: RaisedButton(
                                        shape: RoundedRectangleBorder(
                                            borderRadius:
                                            BorderRadius.circular(8.0)),
                                        elevation: 1.0,
                                        color: lightGreySliderColor,
                                        onPressed: () => () { FeatureDiscovery.clearPreferences(context,
                                          const <String>{ 'favorites', });
                                           },
                                        child: AutoSizeText("Show New Features Again",
                                            maxLines: 1,
                                            style: Theme.of(context)
                                                .textTheme
                                                .subtitle2)),
                                  ),
```

But it didn't seem to show again.  Any idea how to show them again?

**Comment by Condelab** [comment]
to re-show just include this in your 
`init()` 

`FeatureDiscovery.clearPreferences(context, <String>{ 'favorites', });`

it should work, worked for me!

**Comment by ayalma** [comment]
``` FeatureDiscovery.clearPreferences(context, <String>{ 'favorites', });``` just clear the discovery flags 
And if you want to show them again you must call 
```
FeatureDiscovery.discoverFeatures(
  context,
  const <String>{ // Feature ids for every feature that you want to showcase in order.
    'favorites',
  },
);
```

**Comment by jdeltoft** [comment]
Ok, thanks for the info.  I think it must be that I'm doing the README suggestion of using schedulerbinding in init() and I'm wondering if my init() isn't being called again.  I'll play with it.  

The other confusion I had was that I was wanting a way to "skip the tour" of all feature discovery.  For this I just added my own shared preference boolean before calling any discoveries.  Maybe an idea for a API to add (skip all feature discovery by setting them all to already seen?)
