### ISSUE TITLE
Bug with dismiss

### ISSUE THREAD

**Issue by nicolasvahidzein** [ayalma/feature_discovery#18]
Hello, when i dismiss a discovery on a page and i return to that page later, nothing shows but the tap is being capture by the package and the overlay dismissed. This is troublesome and degrades the user performance. Any idea what i can do in this case?

**Comment by ayalma** [comment]
Can you provide some code

**Comment by nicolasvahidzein** [comment]
can't explain it, when i put false in the ondismiss action they don't fire anymore, i had to go another route but it was very strange.
