### ISSUE TITLE
Wonderful wonderful package but causing a lot of issues

### ISSUE THREAD

**Issue by nicolasvahidzein** [ayalma/feature_discovery#20]
Hello, i LOVE your package but i need your help because it's not ready for production.

On dismiss the package is ready to display the overlay but never does, when i stack another page on top of the navigation stack it bugs, it's quite problematic.

Please tell me how we can get rid of some of these bugs.

**Comment by axel-op** [comment]
Hey, does your app work with the version `0.7.0` of this package?

**Comment by nicolasvahidzein** [comment]
No idea @axel-op i will try it and let you know. do i change the package like this:

feature_discovery: 0.7.0
 (removing the ^ ?)

**Comment by axel-op** [comment]
> No idea @axel-op i will try it and let you know. do i change the package like this:
> 
> feature_discovery: 0.7.0
>  (removing the ^ ?)

Exactly, please try and tell me how it goes :)

**Comment by nicolasvahidzein** [comment]
first please explain to me, why is it when i push a new page on top of the stack of a page that has features i dismissed it doesn't trigger? Is that normal or is that what i need to test in version 0.7.0?

**Comment by axel-op** [comment]
That may be related, so try it!

**Comment by nicolasvahidzein** [comment]
Jeez this is tough, i need the features in your 0.8.0 version where i clear the tour data

**Comment by axel-op** [comment]
Ok so post your code at least

**Comment by nicolasvahidzein** [comment]
It won't fit here, not sure what to do.

**Comment by xsahil03x** [comment]
@nicolasvahidzein create a Github gist and share the URL
