### ISSUE TITLE
clear settings without context

### ISSUE THREAD

**Issue by nicolasvahidzein** [ayalma/feature_discovery#21]
Hello, why do we need the context to clear the settings?

i really need to be able to run this without the context and it's quite impossible.

any workaround?

```
                  FeatureDiscovery.clearPreferences(context, <String>{
			'feature_page_accountview_001',
			'feature_page_accountview_002',
			'feature_page_accountview_003',
			'feature_page_menuview_001',
			'feature_page_menuview_002',
			'feature_page_menuview_003',
			'feature_page_menuview_004',
			'feature_page_appbar_001',
			'feature_page_appbar_002',
			'feature_page_appbar_003',
			'feature_page_searchwidget_001',
			'feature_page_mainsearchbar_001',
		});
```

**Comment by axel-op** [comment]
This is because this widget works as an InheritedWidget. The context is used to reach the parent `FeatureDiscovery` widget.

Why can't you pass the context?

**Comment by nicolasvahidzein** [comment]
because i instantiate it from main.dart and if the user needs to be reset i need to do it in Hive which before we run runApp has no context.

**Comment by nicolasvahidzein** [comment]
How do you suggest i clear it then from main() inside main.dart?

**Comment by axel-op** [comment]
The Dart main should be, on Flutter, as empty as possible. So I would first suggest to move your code outside the `main` function.

Secondly, for `clearPreferences` to work, you should call it from under the `FeatureDiscovery` widget (which should be at the top of your widget tree). It will not work otherwise.

**Comment by nicolasvahidzein** [comment]
Ok so this is getting complicated, i am on 0.7.0 but this is not implemented:

clearPreferences

how do i do that in 0.7.0?

**Comment by axel-op** [comment]
Well, I asked you to test the previous version in another issue, that's not related to this one.

**Comment by nicolasvahidzein** [comment]
I'll close this one because i can work around this, i needed to do this for testing a simulation where i would reset the code to simulate a new install but i can just uninstall and reinstall. Not worth wasting your time and mine. So i'll close it.
