### ISSUE TITLE
What is the clean way to determine if an overlay is visible ?

### ISSUE THREAD

**Issue by BazinC** [ayalma/feature_discovery#23]
I would like to know if the API enables us to determine whether any DescribedFeatureOverlay is being displayed or not. Or do we have to handle it externally on our own ?

In the documentation I haven't found nothing but the mention we "cannot use this to check if a feature overlay is being displayed."

Thank you :)

**Comment by ayalma** [comment]
In version 0.10.0 with `FeatureDiscovery.isDisplayed` you can check status of feature.
@BazinC
