### ISSUE TITLE
Allow dismissing to complete the current step

### ISSUE THREAD

**Issue by athornz** [ayalma/feature_discovery#33]
It seems that dismissing the step by tapping the barrier rather than the tap target does not complete the step.

In my case we want the step to be completed regardless of where the user taps. Could this be added?

**Comment by ayalma** [comment]
It's normal action of library
If you want to complete on dismiss just set sharedPref with featureId key and true  value in onDismiss
and that's make the step complete
```
onDismiss: ()async{
       // set bool to shared pref with key same as featureId and value of true
       return true;
},
```

**Comment by athornz** [comment]
Ok, yeah I have a similar work around but I still think it should be a feature of the library. 

A flag to configure whether dismissing completes the step.

**Comment by ayalma** [comment]
Its add extra check to on dismiss while it's not necessary

**Comment by athornz** [comment]
It's a shame this was closed. This is a nice library and this small feature would be useful to me and others as well.

It may not be necessary for your use case, or every use case, but it would still be useful.

I guess I'll look for another library.

**Comment by ayalma** [comment]
As you wish
