### ISSUE TITLE
DismissAll don't complete all the steps.

### ISSUE THREAD

**Issue by javiermedina-c** [ayalma/feature_discovery#34]
Hi, I'm currently working with version 0.10.0. I'm implementing a button to dismiss all the next steps, when the function is executed dismiss all the steps as expected. But after that, when discoverFeatures is called again, run these steps again.

Maybe is the behavior expected, but this can be a new feature for a button to complete all the steps and not showing again. 

Regards.

**Comment by javiermedina-c** [comment]
Any update? 

I'm working with the current version 0.12.0+2

Regards.

**Comment by ayalma** [comment]
Yes as you mentioned this is the behavior expected

**Comment by dev-thinks** [comment]
As this is expected behavior, you can set the preferences of all your featureIds to true to complete all the steps when dismissing, @javiermedina-c
