### ISSUE TITLE
FeatureDiscory is on big screen a little bit buggy

### ISSUE THREAD

**Issue by AndroidNils** [ayalma/feature_discovery#37]
## Demo
![IMG_E398006B424A-1](https://user-images.githubusercontent.com/24459435/87228246-359eba80-c3a0-11ea-915d-b8d7e33731e0.jpeg)

## Steps to reproduce
1. Use Example
2. Run on a big screen, like PC with Flutter web

**Comment by ayalma** [comment]
Test with  last version version, please.

**Comment by AndroidNils** [comment]
Yes, it works with the newest version 👍
