### ISSUE TITLE
it runs only the first time, after that no popup appears

### ISSUE THREAD

**Issue by ayazkhalid** [ayalma/feature_discovery#41]
It runs only when app start for the first time after that i have to clear the cache to run it again

**Comment by ayalma** [comment]
read readme plz!!!!

**Comment by X-Wei** [comment]
Seems `FeatureDiscovery.clearPreferences()` [doesn't work](https://github.com/X-Wei/flutter_catalog/blob/678b35b871a041aceb3eb291daa9781e08bb8e16/lib/routes/plugins_feature_discovery_ex.dart#L154) with version=`^0.13.0`? For now I use version `0.12.0` instead.

(Correct me if I'm doing something wrong in the above code, thanks!)

**Comment by ayalma** [comment]
Try to use  
`
      FeatureDiscovery.withProvider(
          persistenceProvider: SharedPreferencesProvider('prefix'),
          child: MyHomePage(title: 'Flutter Feature Discovery'),
       ),
`

**Comment by ayalma** [comment]
Thanks for your participation
I fixed issue and published new version
Best regards
Ali

**Comment by X-Wei** [comment]
Now it works perfectly, thanks !
