### ISSUE TITLE
Allow colored area to dismiss on tap

### ISSUE THREAD

**Issue by michinchin** [ayalma/feature_discovery#5]
Hi! Love this plugin. Wanted to see if you'd be willing to add an option for dismissing the overlay by tapping on the color. On smaller screens especially, the colored region often takes up a majority of the screen and make it hard to tap out. Thanks!

**Comment by creativecreatorormaybenot** [comment]
@axel-op and me created quite a big update to the plugin over at https://github.com/axel-op/feature_discovery. You could create a PR there and add this functionality. If you want, you can also create an issue there and then I could add this. It is a really simple adjustement as it only requires one parameter and one `onTap` with a condition.

**Comment by ayalma** [comment]
I think this issue is resolved with  barrierDismissible #22 
Thank's to @xsahil03x

**Comment by kafein** [comment]
@ayalma I think @michinchin asks for colored area. not outside area. Can we reopen this? I need this feature too. Thanks

**Comment by ganeshrvel** [comment]
i have raised a pr for the same https://github.com/ayalma/feature_discovery/pull/46

**Comment by ayalma** [comment]
Issue resolved in `12.0.1`
