### ISSUE TITLE
Overlay appears panned to a side

### ISSUE THREAD

**Issue by jagomf** [ayalma/feature_discovery#51]
I have a `DescribedFeatureOverlay` on a center-docked FAB, and **only on iOS** the overlay appears panned to the left side:

![sorry, I don't know how to create a thumbnail in github](https://user-images.githubusercontent.com/4032522/95635334-6a4c0c00-0a8c-11eb-96be-6f7a167a5107.png)

(In the screenshot, the FAB's icon is pulsating, that's why it looks so big).

As mentioned, it is only happening on iOS (on Android it looks fine).

This is my code in case it helps:

```dart
DescribedFeatureOverlay(
  featureId: featureId,
  targetColor: localTheme.accentColor,
  tapTarget: Icon(CupertinoIcons.person_add_solid),
  contentLocation: ContentLocation.above,
  title: const Text('More fun with Friends'),
  child: FloatingActionButton(
    child: const Icon(CupertinoIcons.person_add_solid),
    onPressed: ...
  )
  description: Column(
    children: [
      const Text('Add your Friends [...]'),
      Padding(
        padding: const EdgeInsets.symmetric(vertical: 16),
        child: RaisedButton(child: const Text('GOT IT!'), onPressed: () { FeatureDiscovery.completeCurrentStep(context); }),
      )
    ],
  )
)
```

Also as mentioned, FAB's `floatingActionButtonLocation` is `FloatingActionButtonLocation.centerDocked`.

Why is that overlay panned? What can I do? Is that a bug?

Using Flutter 1.22, macOS 10.15.7, Xcode 12.0.1, feature_discovery: ^0.12.0+2

**Comment by ayalma** [comment]
Try to use ```  overflowMode: OverflowMode.extendBackground,``` on ```DescribedFeatureOverlay```

**Comment by jagomf** [comment]
Background gets wider and text can be read, but it is still panned to the left side, **not centered**.

![image](https://user-images.githubusercontent.com/4032522/99876176-5819cd80-2bf5-11eb-9b38-ec311cc9d320.png)

**Comment by ayalma** [comment]
Can you provide some code pls
