### ISSUE TITLE
A 'skip' button for dismissing the walkthrough

### ISSUE THREAD

**Issue by barun1997** [ayalma/feature_discovery#53]
What's the best way to implement a "Skip" button in conjunction with the package? 

I don't want to use both backgroundDismissible as well as barrierDismissible and instead have a skip button for the user to dismiss the walkthrough.

**Comment by CaptainDario** [comment]
@barun1997 did you figure this out?

**Comment by barun1997** [comment]
@CaptainDario It was a long time ago, but I think I forked it and implemented a Skip button myself: https://github.com/barun1997/feature_discovery
