### ISSUE TITLE
DescribedFeatureOverlay for BottomNavigationBarItems

### ISSUE THREAD

**Issue by darthsitthiander** [ayalma/feature_discovery#60]
Great work on this package! The only thing I can't seem to get working is to have the bottom navigation bar display the feature discovery overlay since I can't return a Widget type as BottomNavigationBar requires its items to be of type BottomNavigationBarItem, which DescribedFeatureOverlay is not:

```dart
Scaffold(
  [...]
  bottomNavigationBar: BottomAppBar(
    [...]
    child: BottomNavigationBar(
      [...]
      items: [
        DescribedFeatureOverlay( // This does not work because items requires type BottomNavigationBarItem
          [...]
          child: BottomNavigationBarItem(
            icon: Icon(item.icon),
            label: item.title,
          ),
        ),
      ],
    ),
  ),
);
```

The valid code would be like this:
```dart
Scaffold(
  [...]
  bottomNavigationBar: BottomAppBar(
    [...]
    child: BottomNavigationBar(
      [...]
      items: [
        BottomNavigationBarItem( // need to wrap this with DescribedFeatureOverlay
          icon: Icon(item.icon),
          label: item.title,
        ),
      ],
    ),
  ),
);
```

I've been trying for so long now to find a solution to this.
How can I wrap the BottomNavigationBarItem with the DescribedFeatureOverlay?
Is this a limitation of Flutter or is there a way of doing this?

**Comment by ayalma** [comment]
As workaround you can wrap icon widget on BottomNavigationBarItem with DescribedFeatureOverlay
