### ISSUE TITLE
`backgroundDismissible: true` or `backgroundDismissible` Cause to close the hole flow and not just skip the current discovery

### ISSUE THREAD

**Issue by danielgomezrico** [ayalma/feature_discovery#77]
Hi

If I set `barrierDismissible` or `backgroundDismissible` like:

```dart
 DescribedFeatureOverlay(
        barrierDismissible: true,
);

// Or
 DescribedFeatureOverlay(
        backgroundDismissible: true,
);
```

Together with a list of IDs like:

```dart
FeatureDiscovery.discoverFeatures(context, {
        dashboardFiltersId,
        forYouMenuOptionId,
        myHausMenuOptionId,
      });
```

It causes that the hole discovery is stoped after touching outside

# Expected
It should step over the next step and not stop the hole discovery

**Comment by GaelleJoubert** [comment]
You can use the "on dismiss" parameter from `DescribeFeatureOverlay` :
If you do something like :

```
onBackgroundTap: ()async{ FeatureDiscovery.completeCurrentStep(context); return false;},
onDismiss:  ()async{ FeatureDiscovery.completeCurrentStep(context); return false;},
```

It should do what you are looking for :)

Documentation :
https://pub.dev/documentation/feature_discovery/latest/feature_discovery/DescribedFeatureOverlay/onDismiss.html

**Comment by Ahmadre** [comment]
> return false;

Thanks @GaelleJoubert :) your comment helped me.
