### ISSUE TITLE
Updating pubspec.yaml to provider 6.0.0 leads to version solving failed with feature_discovery 0.14.0

### ISSUE THREAD

**Issue by pureimpro** [ayalma/feature_discovery#78]
Because feature_discovery 0.14.0 depends on provider ^5.0.0 and no versions of feature_discovery match >0.14.0 <0.15.0, feature_discovery ^0.14.0 requires provider ^5.0.0.

**Comment by P-B1101** [comment]
still waiting...

**Comment by pureimpro** [comment]
feature_discovery updated
