### ISSUE TITLE
Flutter 3 compatibility

### ISSUE THREAD

**Issue by P-B1101** [ayalma/feature_discovery#91]
Thanks again for the awesome package. please consider updating the package and fixing flutter 3 warnings.

`Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null`

**Comment by vytautas-pranskunas-** [comment]
Any merge? New version?

**Comment by P-B1101** [comment]
I don't know why @ayalma  won't merge.

**Comment by TheArchitect123** [comment]
I've forked this library and will be maintaining it on my own profile. You can find the latest one here.

https://github.com/ayalma/feature_discovery/issues/100
@P-B1101  @vytautas-pranskunas-

**Comment by ayalma** [comment]
New Version  to solve issue with flutter 3  (0.14.2)
